DEFAULT_DENSE_MODEL = 'google/embeddinggemma-300m'
DEFAULT_SPARSE_MODEL = 'Qdrant/bm25'
DEFAULT_LATE_INTERACTION_MODEL = 'colbert-ir/colbertv2.0'

DEFAULT_QDRANT_URL = 'http://localhost:6333'
DEFAULT_QDRANT_COLLECTION = 'gwaihir_chunks'
DEFAULT_DENSE_VECTOR_NAME = 'dense'
DEFAULT_SPARSE_VECTOR_NAME = 'sparse'
DEFAULT_LATE_INTERACTION_VECTOR_NAME = 'late_interaction'

DEFAULT_CHUNK_SIZE = 512
DEFAULT_CHUNK_OVERLAP = 64
DEFAULT_CHUNK_TOKENIZER_NAME = DEFAULT_DENSE_MODEL

DEFAULT_QDRANT_TIMEOUT_SECONDS = 300
DEFAULT_UPSERT_SLICE_SIZE = 8

DEFAULT_RETRIEVE_LIMIT = 5
DEFAULT_PREFETCH_LIMIT = 24
